#!/bin/bash
#
# For use with i3:
#   bindsym $mod+e exec --no-startup-id "dmenu_getkey"

set -ue
set -o pipefail

CACHE=${XDG_CACHE_HOME:-$HOME/.cache}/getkey

[ -d $CACHE ] || install -m 0700 -d $CACHE

GETKEY=~/.local/bin/getkey

getkey() {
    $GETKEY --list-cache=$CACHE/list-cache "$@"
}

getkey -l | dmenu | while read key; do
    getkey -s $key
done
